HealthAppAdminPortal/Models/Notification.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HealthAppAdminPortal.Models
{
    public class Notification
    {
        public int Id { get; set; }
        [MaxLength(500)]
        public string NotificationText { get; set; }
        [MaxLength(500)]
        public string? NotificationUrl { get; set; }
        public bool UrlActive { get; set; }
    }
}

HealthAppAdminPortal/Controllers/NotificationController.cs
using HealthAppAdminPortal.Data;
using HealthAppAdminPortal.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace HealthAppAdminPortal.Controllers
{
    public class NotificationController : Controller
    {
        private readonly DataContext _context;
        public NotificationController(DataContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var result = _context.Notifications.ToList();
            return View(result);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id, NotificationText, NotificationUrl, UrlActive")] Notification notification)
        {
            try
            {
                _context.Add(notification);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Notification");
            }
            catch
            {
                return View(notification);
            }

        }

        public IActionResult Edit(int Id)
        {
            var result = _context.Notifications.Where(x => x.Id == Id).FirstOrDefault();
            return View(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int Id, [Bind("Id, NotificationText, NotificationUrl, UrlActive")] Notification notification)
        {
            if (Id != notification.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(notification);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!notificationExists(notification.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(notification);

        }

        public async Task<IActionResult> Delete(int Id)
        {
            var result = await _context.Notifications.Where(x => x.Id == Id).FirstOrDefaultAsync();
            if (result != null)
            {
                _context.Notifications.Remove(result);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Notification");
        }

        private bool notificationExists(int id)
        {
            return (_context.Notifications?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

HealthAppAdminPortal/Controllers/NotificationIntervalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HealthAppAdminPortal.Data;
using HealthAppAdminPortal.Models;

namespace HealthAppAdminPortal.Controllers
{
    public class NotificationIntervalsController : Controller
    {
        private readonly DataContext _context;

        public NotificationIntervalsController(DataContext context)
        {
            _context = context;
        }

        //Not Needed
        //// GET: NotificationIntervals
        //public async Task<IActionResult> Index()
        //{
        //      return _context.NotificationIntervals != null ? 
        //                  View(await _context.NotificationIntervals.ToListAsync()) :
        //                  Problem("Entity set 'DataContext.NotificationIntervals'  is null.");
        //}

        //// GET: NotificationIntervals/Details/5
        //public async Task<IActionResult> Details(int? id)
        //{
        //    if (id == null || _context.NotificationIntervals == null)
        //    {
        //        return NotFound();
        //    }

        //    var notificationInterval = await _context.NotificationIntervals
        //        .FirstOrDefaultAsync(m => m.Id == id);
        //    if (notificationInterval == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(notificationInterval);
        //}

        //// GET: NotificationIntervals/Create
        //public IActionResult Create()
        //{
        //    return View();
        //}

        //// POST: NotificationIntervals/Create
        //// To protect from overposting attacks, enable the specific properties you want to bind to.
        //// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("Id,IntervalTime")] NotificationInterval notificationInterval)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _context.Add(notificationInterval);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(notificationInterval);
        //}

        // GET: NotificationIntervals/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.NotificationIntervals == null)
            {
                return NotFound();
            }

            var notificationInterval = await _context.NotificationIntervals.FindAsync(id);
            if (notificationInterval == null)
            {
                return NotFound();
            }
            return View(notificationInterval);
        }

        // POST: NotificationIntervals/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,IntervalTime")] NotificationInterval notificationInterval)
        {
            if (id != notificationInterval.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(notificationInterval);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NotificationIntervalExists(notificationInterval.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), nameof(Notification));
            }
            return RedirectToAction(nameof(Index),nameof(Notification));
        }

        //// GET: NotificationIntervals/Delete/5
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null || _context.NotificationIntervals == null)
        //    {
        //        return NotFound();
        //    }

        //    var notificationInterval = await _context.NotificationIntervals
        //        .FirstOrDefaultAsync(m => m.Id == id);
        //    if (notificationInterval == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(notificationInterval);
        //}

        //// POST: NotificationIntervals/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    if (_context.NotificationIntervals == null)
        //    {
        //        return Problem("Entity set 'DataContext.NotificationIntervals'  is null.");
        //    }
        //    var notificationInterval = await _context.NotificationIntervals.FindAsync(id);
        //    if (notificationInterval != null)
        //    {
        //        _context.NotificationIntervals.Remove(notificationInterval);
        //    }
            
        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        private bool NotificationIntervalExists(int id)
        {
          return (_context.NotificationIntervals?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

HealthAppAdminPortal/Views/Notification/Create.cshtml
@model Notification
@{
}
<h1>Create New Notification</h1>
<form asp-controller="Notification" asp-action="Create" class="mb-3">
    <div class="form-group">
        <input type="hidden" asp-for="Id">
    </div>
    <div class="form-group mb-2">
        <label asp-for="NotificationText" class="control-label">Notification Text</label>
        <input asp-for="NotificationText" class="form-control">
        <span asp-validation-for="NotificationText" class="text-danger"></span>
    </div>
    <div class="form-group mb-2">
        <label asp-for="NotificationUrl" class="control-label"></label>
        <input asp-for="NotificationUrl" class="form-control">
        <span asp-validation-for="NotificationUrl" class="text-danger"></span>
    </div>
    <div class="form-check form-switch mb-3">
        <input class="form-check-input" type="checkbox" asp-for="UrlActive">
        <label class="form-check-label" asp-for="UrlActive">Check switch to activate Notification</label>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
<a asp-controller="Notification" asp-action="Index">Back to Notification List</a>

HealthAppAdminPortal/Views/Notification/Edit.cshtml
@model Notification
@{
}

<form asp-controller="Notification" asp-action="Edit" class="mb-3">
    <div class="form-group">
        <input type="hidden" asp-for="Id">
    </div>
    <div class="form-group mb-2">
        <label asp-for="NotificationText" class="control-label">Notification Text</label>
        <input asp-for="NotificationText" class="form-control">
        <span asp-validation-for="NotificationText" class="text-danger"></span>
    </div>
    <div class="form-group mb-2">
        <label asp-for="NotificationUrl" class="control-label"></label>
        <input asp-for="NotificationUrl" class="form-control">
        <span asp-validation-for="NotificationUrl" class="text-danger"></span>
    </div>
    <div class="form-check form-switch mb-3">
        <input class="form-check-input" type="checkbox" asp-for="UrlActive">
        <label class="form-check-label" asp-for="UrlActive">Check switch to activate Notification</label>
    </div>
    <button type="submit" class="btn btn-primary">Confirm Changes</button>
</form>
<a asp-controller="Notification" asp-action="Index">Back to Notification List</a>

HealthAppAdminPortal/Views/Notification/Index.cshtml
@model IList<Notification>
@{
}

<div class="d-flex justify-content-between">
    <div class="mb-3">
        <a class="btn btn-primary" asp-controller="Notification" asp-action="Create">Create New Notification Data</a>
    </div>

    <div class="mb-3">
        <a class="btn btn-primary" asp-controller="NotificationIntervals" asp-action="Edit" asp-route-Id="1">Notification Interval Setting</a>
    </div>
</div>

<div class="mt-3">
    <table class="table table-sm">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Notification Text</th>
                <th scope="col">Url</th>
                <th scope="col"> </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <th scope="row">@item.Id</th>
                    <td>@item.NotificationText</td>
                    <td>
                        <a href="https://@item.NotificationUrl" target="_blank">@item.NotificationUrl</a>

                </td>
                    <td>
                        <a class="btn btn-primary" asp-controller="Notification" asp-action="Edit" asp-route-Id="@item.Id">Edit</a>
                        <a class="btn btn-danger" asp-controller="Notification" asp-action="Delete" asp-route-Id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>